### ISSUE TITLE
Use a linter and code formatter.

### ISSUE THREAD

**Issue by JohanG2012** [MrKhoaBean/flappingonline#2]
Use a linter and code formatter to help you write easy-to-read code.

I suggest ESLint.
https://www.npmjs.com/package/eslint

With airbnb-config
https://www.npmjs.com/package/eslint-config-airbnb

And prettier:
https://blog.echobind.com/integrating-prettier-eslint-airbnb-style-guide-in-vscode-47f07b5d7d6a

**Comment by beanbocchi** [comment]
I've never heard about something called "lint", I probably need more time to learn it :(

**Comment by JohanG2012** [comment]
This link explains it pretty well :) https://blog.echobind.com/integrating-prettier-eslint-airbnb-style-guide-in-vscode-47f07b5d7d6a
