### ISSUE TITLE
self-documenting code.

### ISSUE THREAD

**Issue by JohanG2012** [MrKhoaBean/flappingonline#3]
Take this code as an example.

https://github.com/MrKhoaBean/flappingonline/blob/1983057865ead285edd0a3114a430f34b74695d9/server.js#L48-L56

Months after you have written this, it might be hard to understand what you did and why. This is why comments are important. 

Lets say you hade this comment.

```
// Add to score if new high score adds it to the high score.
```

However, you should always see an added comment as a failure. It basically means "my code was so hard to understand, that I had to add a comment". Is better to make use of variables and functions. For example, the code above could be written like this:

```
const incrementScore = (score, socket) => score[socket.id].score++

const isNewHighScore = (score, socket) => score[socket.id].score > score[socket.id].high

const setHighScore = (score, socket) => score[socket.id].high = score[socket.id].score;

const handleRankUp = (score, socket) => {
  incrementScore(score, socket);
  if (isNewHighScore(score, socket)) {
	setHighScore(score, socket)
  }
}

socket.on('plus', ()=>{
		if (rank){
			handleRankUp(score, socket)
		}
		
	})
```

Pretty easy to read the code now right?

You could even add error handling.

```
const incrementScore = (score, socket) => score[socket.id].score++

const isNewHighScore = (score, socket) => score[socket.id].score > score[socket.id].high

const setHighScore = (score, socket) => score[socket.id].high = score[socket.id].score;

const handleRankUp = (score, socket) => {
  try {
    incrementScore(score, socket);
    if (isNewHighScore(score, socket)) {
	setHighScore(score, socket)
    }
  } catch (error) {
    // Handle error here
  }

}

socket.on('plus', ()=>{
		if (rank){
			handleRankUp(score, socket)
		}
		
	})
```

**Comment by beanbocchi** [comment]
That 's time I am very stupid in writting cleaning code. Okay, I will make it better!
